apiVersion: v1
kind: Service
metadata:
  name: nodejs-cloudtris-frontend
  labels:
    app: nodejs-cloudtris
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: nodejs-cloudtris
    tier: frontend
  ports:
  - port: 3000
    targetPort: http-server