apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-cloudtris
    tier: db
  name: nodejs-cloudtris-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: nodejs-cloudtris
    tier: db
